# ---------------------------------------------------------
# General Settings
# ---------------------------------------------------------
set -g mouse on
set -g status-interval 5

# ---------------------------------------------------------
# Key Bindings
# ---------------------------------------------------------
set -g prefix C-s
bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

bind -n M-h previous-window
bind -n M-l next-window

# Keep these just for instances where you cant use the ctrl key
bind -n M-H select-pane -L
bind -n M-J select-pane -D
bind -n M-K select-pane -U
bind -n M-L select-pane -R

bind - split-window -v
bind \\ split-window -h

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"

# ---------------------------------------------------------
# Visuals
# ---------------------------------------------------------
# Lock the background to your terminal's default color, text to white
set -g status-style bg="#373b41",fg="#c5c8c6"
set -g status-position bottom

set -g window-status-format " #I:#W "
set -g window-status-current-style bg=green,fg=black
set -g window-status-current-format " [#I:#W] "

set -ag terminal-overrides ",xterm-256color:RGB"
set -g default-terminal "tmux-256color"

# ---------------------------------------------------------
# Left Side: Session Name
# ---------------------------------------------------------
set -g status-left-length 40
set -g status-left "#[fg=green,bold][#S] #[default]"

# ---------------------------------------------------------
# Right Side: Modules
# ---------------------------------------------------------
set -g status-right-length 150

# The string is built using color tags (e.g., #[fg=cyan]) and variables.
# 1. NET: Uses 'ip route' to find the active connection (e.g., wlan0 or eth0)
# 3. CPU: Uses the tmux-cpu plugin
# 4. BAT: Uses the tmux-battery plugin
# 5. TIME: Standard 24-hour clock

set -g status-right "#[fg=magenta]NET: #(tmux-network-name) #[default]| #[fg=yellow]CPU: #{cpu_percentage} #[default]| #[fg=red]BAT: #(tmux-battery-weighted) #[default]| #[fg=white,bold]%H:%M "
