# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-148f72bf-ad36-4b33-9105-36fc20fd58c8";
      fsType = "ext4";
    };

  # File System
  boot.initrd.luks.devices."luks-148f72bf-ad36-4b33-9105-36fc20fd58c8".device = "/dev/disk/by-uuid/148f72bf-ad36-4b33-9105-36fc20fd58c8";

  # Swap
  boot.initrd.luks.devices."luks-d7f51b85-a75a-4702-88a5-006f3732fecb".device = "/dev/disk/by-uuid/d7f51b85-a75a-4702-88a5-006f3732fecb";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9A51-3AB4";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-d7f51b85-a75a-4702-88a5-006f3732fecb"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
